name: Release LaTeX document
on: 
  workflow_dispatch:
    inputs:
      root:
        description: Specify which template folder to be compiled
        type: string
        required: true
      release_name:
        description: A name of a release
        type: string
        required: true
      version:
        description: A version to release
        type: string
        required: true
      texfile:
        description: Name of the main LaTeX file (must be in root; without extension)
        type: string
        required: true
      deploy:
        description: Tick the box to deploy the document to GitHub Pages
        type: boolean
        required: true

permissions:
  contents: write
  packages: write

env:
  DEPLOY_DIR: 'github_deploy'
  DEPLOY_BRANCH: 'build'
  OUTPUT_DIR: 'github_artifacts'

jobs:
  build:
    if: ${{ github.actor == 'jate-koh'}}
    name: Build document
    uses: ./.github/workflows/build-latex.yaml
    with:
      texfile: ${{ github.event.inputs.texfile }}
      root: ${{ github.event.inputs.root }}

  deploy:
    if: ${{ github.event.inputs.deploy == true }}
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: List files
        run: ls -R
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: ./${{ env.OUTPUT_DIR }}

      - name: List files
        run: ls -R
      - name: Move files
        run: mkdir -p ${{ env.DEPLOY_DIR }} && mv ${{ env.OUTPUT_DIR }}/*/* ${{ env.DEPLOY_DIR  }}
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ${{ env.DEPLOY_DIR }}
          publish_branch: ${{ env.DEPLOY_BRANCH}}
          force_orphan: true

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: List files
        run: ls -R
      - name: Download PDF artifact
        uses: actions/download-artifact@v2
        with:
          path: ./${{ env.OUTPUT_DIR }}
      
      - name: List files
        run: ls -R
      - name: Compressed target template directory
        run: zip -r ${{ github.event.inputs.root }}.zip ${{ github.event.inputs.root }}/*

      # - name: Update CHANGELOG
      #   id: changelog
      #   uses: requarks/changelog-action@v1
      #   with:
      #     token: ${{ secrets.GH_TOKEN }}
      #     tag: ${{ github.events.inputs.root }}

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ github.event.inputs.release_name }}
          body: |
            Release ${{ github.event.inputs.version }}
            Note: This is an auto-generated release. 
            You may download the PDF and template zip file from the assets below.
          token: ${{ secrets.GH_TOKEN }}

      - name: List files
        run: ls -R
      - name: Upload PDF artifact as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./${{ env.OUTPUT_DIR }}/${{ github.event.inputs.texfile }}.pdf
          asset_name: ${{ github.event.inputs.texfile }}.pdf
          asset_content_type: application/pdf

      - name: Upload ZIP template as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: ${{ github.event.inputs.root }}.zip
          asset_content_type: application/zip
